.TH "bankCardBuilder" 3 "Mon Apr 9 2018" "Version 1.0" "TPCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bankCardBuilder \- билдер для банковскоё карты  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <bankCardBuilder\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbankCardBuilder\fP ()"
.br
.RI "инициализация "
.ti -1c
.RI "void \fBsetNumber\fP (const std::string &number)"
.br
.RI "уствновка номера карты "
.ti -1c
.RI "void \fBsetEndDate\fP (const std::string &endDate)"
.br
.RI "установка даты окончания карты "
.ti -1c
.RI "void \fBsetCsvCode\fP (const std::string &csvCode)"
.br
.RI "установка csv кода "
.ti -1c
.RI "void \fBsetCode\fP (const std::string &code)"
.br
.RI "установка пинкода "
.ti -1c
.RI "\fBCard\fP \fBcreateBankCard\fP ()"
.br
.RI "создание карты с банковскими данными "
.in -1c
.SH "Detailed Description"
.PP 
билдер для банковскоё карты 
.SH "Member Function Documentation"
.PP 
.SS "\fBCard\fP bankCardBuilder::createBankCard ()"

.PP
создание карты с банковскими данными 
.PP
\fBReturns:\fP
.RS 4
карта 
.RE
.PP

.SS "void bankCardBuilder::setCode (const std::string & code)"

.PP
установка пинкода 
.PP
\fBParameters:\fP
.RS 4
\fIcode\fP значение 
.RE
.PP

.SS "void bankCardBuilder::setCsvCode (const std::string & csvCode)"

.PP
установка csv кода 
.PP
\fBParameters:\fP
.RS 4
\fIcsvCode\fP значение 
.RE
.PP

.SS "void bankCardBuilder::setEndDate (const std::string & endDate)"

.PP
установка даты окончания карты 
.PP
\fBParameters:\fP
.RS 4
\fIendDate\fP значение 
.RE
.PP

.SS "void bankCardBuilder::setNumber (const std::string & number)"

.PP
уствновка номера карты 
.PP
\fBParameters:\fP
.RS 4
\fInumber\fP значение 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TPCard from the source code\&.
