.TH "PassportCard" 3 "Mon Apr 9 2018" "Version 1.0" "TPCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PassportCard
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMasterCard\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPassportCard\fP (const std::shared_ptr< \fBCard\fP > &card)"
.br
.RI "считывание карты с паспортом "
.ti -1c
.RI "\fBPassportCard\fP (std::string firstName, std::string lastName, std::string bornDate, std::string personalCode)"
.br
.RI "создание карты с паспортом "
.ti -1c
.RI "std::string \fBgetFirstName\fP () const"
.br
.RI "имя "
.ti -1c
.RI "std::string \fBgetSecondName\fP () const"
.br
.RI "фамилия "
.ti -1c
.RI "std::string \fBgetBornDate\fP () const"
.br
.RI "дата рождения "
.ti -1c
.RI "std::string \fBgetPersonalCode\fP () const"
.br
.RI "номер паспорта "
.ti -1c
.RI "\fBCard\fP \fBgetCard\fP () const"
.br
.RI "получение созданной карты "
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBcardId\fP = 2"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PassportCard::PassportCard (const std::shared_ptr< \fBCard\fP > & card)\fC [explicit]\fP"

.PP
считывание карты с паспортом 
.PP
\fBParameters:\fP
.RS 4
\fIcard\fP 
.RE
.PP

.SS "PassportCard::PassportCard (std::string firstName, std::string lastName, std::string bornDate, std::string personalCode)"

.PP
создание карты с паспортом 
.PP
\fBParameters:\fP
.RS 4
\fIfirstName\fP имя 
.br
\fIlastName\fP фамилия 
.br
\fIbornDate\fP дата рождения 
.br
\fIpersonalCode\fP номер паспорта в формате строки 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "std::string PassportCard::getBornDate () const"

.PP
дата рождения 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "\fBCard\fP PassportCard::getCard () const"

.PP
получение созданной карты 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "std::string PassportCard::getFirstName () const"

.PP
имя 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "std::string PassportCard::getPersonalCode () const"

.PP
номер паспорта 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "std::string PassportCard::getSecondName () const"

.PP
фамилия 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for TPCard from the source code\&.
