.TH "Wrong_Card_Type_Exception" 3 "Mon Apr 9 2018" "Version 1.0" "TPCard" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Wrong_Card_Type_Exception
.SH SYNOPSIS
.br
.PP
.PP
Inherits exception\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "const char * \fBwhat\fP () const override  throw ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for TPCard from the source code\&.
